### ISSUE TITLE
Question regarding dataset downloading

### ISSUE THREAD

**Issue by itsmag11** [clovaai/voxceleb_trainer#149]
Dear authors,

I am new to this VoxCeleb dataset and have trouble downloading the videos from the scripts given. I follow the instructions in the Data Preparation section but only get the audio part of the dataset. May I ask how I can download the videos (in .mp4 or .m4v format maybe) containing both visual and audio parts? Thanks in advance.

Regards

**Comment by padiarushi3012** [comment]
Hey @itsmag11 

 I found this helpful - https://github.com/kaneelgit/msi_voxceleb/blob/main/video_classification_2d.ipynb

**Comment by itsmag11** [comment]
> 

Thanks @padiarushi3012 !

I found the test set downloading command from the post you gave. For anyone who also have the same problem, I post the command here for easy reference:
`!wget "https://thor.robots.ox.ac.uk/~vgg/data/voxceleb/vox1a/vox2_test_mp4.zip"`

Moreover, I found the dataset page provided by the author which is much clearer than that hosted on the https://www.robots.ox.ac.uk/ website. The link is [here](http://mm.kaist.ac.kr/voxceleb/). Everything related to downloading the dataset should be clear on this page.

Then I'll close the issue.

**Comment by Mercurise** [comment]
> 

Hi @itsmag11 , 

Thanks for the response, and I've fetched the username and password via the form. Turns out they are sending the exact same username and password pairs (I got the same pair as this thread posted in Apr 2021 https://github.com/clovaai/voxceleb_trainer/issues/117#issue-933475286). My rerunning `prep_data.py` still gave me the 404 issues, looks like their internal issues on the dataset maintenance. 

Regarding the mirror page you shared, it looks much clear and well-organised. Big thanks! I'm playing with the verification data and the data can be downloaded with the given username and password pair. I'll probably manually download my interested data.

Again, thanks a lot. Have a nice day.

**Comment by itsmag11** [comment]
@Mercurise Not a problem.

And for the downloading issue, I just thought of that I have changed all urls of files in `lists/fileparts.txt` from `http://www.robots.ox.ac.uk/` to `http://thor.robots.ox.ac.uk/`  following someone's solution somewhere. Hope it solves your problem.
